# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Created YML from Azure Portal - Azure App Service Deployment Center (creates publish profile)
# Then pulled yml to local computer to edit

# FOLDER STRUCTURE
# - client
# - server
# - dist-client
# - dist-server (final packaged asset)

name: server multi-file-upload 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: build client to ../dist-client
        run: |
          cd client
          npm install
          npm run build:to:server --if-present
          ls 
          cd ../ && ls -la
        env: # Or as an environment variable
          REACT_APP_SERVER_BASE_URL: ${{ secrets.REACT_APP_SERVER_BASE_URL }}
          REACT_APP_MICROSOFT_APPLICATION_INSIGHTS: ${{ secrets.REACT_APP_MICROSOFT_APPLICATION_INSIGHTS }}

      - name: build server with client to ../dist-server
        run: |
          cd server
          npm install
          npm run build:publish --if-present    
          ls 
          cd ../ && ls -la  
      - name: cp ./dist-client to ./dist-server/public
        run: |
          ls -la
          cp -r dist-client/ dist-server/public/
          cd dist-server/public && ls -la
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist-server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'multi-file-upload'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1234 }}
          package: .
